include ../config.mk

SUBDIRS = pitch-roll-cabinet

install-examples:
	mkdir -p $(DESTDIR)$(EMC2_HOME)/share/linuxcnc-fgfdm/examples
	cp -R $(SUBDIRS) $(DESTDIR)$(EMC2_HOME)/share/linuxcnc-fgfdm/examples

